version: '3'

services:
  classyfire-web:
    networks:
      - default
      - nginx-net
    environment:
      VIRTUAL_HOST: classyfire.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: classyfire.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net