version: '3'
services:
  classyfire-web:
    build: .
    container_name: classyfireproxy
    ports:
    - "5057:5000"
    command: /app/run_server.sh
    depends_on: 
      - classyfire-redis
      - classyfire-mqrabbit
    networks:
      - default
    volumes:
    - ../cache:/data
    - ../logs:/app/logs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8000M

  classyfire-worker1:
    build: .
    container_name: classyfireproxy_worker1
    command: /app/run_celery_worker.sh
    restart: unless-stopped
    depends_on: 
      - classyfire-redis
      - classyfire-mqrabbit
    networks:
      - default
    volumes:
    - ../cache:/data
    deploy:
      resources:
        limits:
          memory: 4000M

  classyfire-redis:
    image: redis
    container_name: classyfireproxy_redis
    networks:
      - default
    volumes:
    - ../cache:/data
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          memory: 2000M

  classyfire-mqrabbit:
    image: rabbitmq:latest
    container_name: classyfireproxy_mqrabbit
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 8000M
  


